# C. Cho 
##############
# LIBRAIRIES #
##############
import numpy as np
import matplotlib.pyplot as plt
import random
from matplotlib import cm
from copy import deepcopy


###########
# PROBLEM #
###########
"""
Let (X, Y) be two vectors in R^n x R^n.
The coordinates (xi, yi) of X and Y form coordinate couples
which designate points on a graph.

We want to fit our Y points with a pair (a, B) in R x R^n such that
Y ~ aX + B.

In practice we will always have an error vector eps such that
Y = aX + B + eps.

The idea is to approximate the vector Y by a Ŷ such that
Ŷ = aX + B and eps = Y - Ŷ.
For this we must find the best pair (a, b).

Ŷ = aX + b = a(x1, ..., xn) + b(1, ..., 1)
For all i in {1, ..., n}: ŷ_i = a * x_i + b

Let us define the vector w = (a, b).

We can rewrite the matrix equation as:

        [[x1   1],
Ŷ =     [..   ..] * (a, b)^T
        [xn   1]]

Let w = (a, b)^T in M(2,1)(R)
and A = [[x1   1], [...  ...], [xn   1]] in M(n,2)(R)

We obtain the equation Ŷ = A w  (E)

In the best case eps = (0, ..., 0),
that is Ŷ = Y. In that case we directly have w = Ŷ A^{-1}.

In practice this is not the case. Let us analyze (E).

We seek w = argmin(||eps||) = argmin(||Y - Ŷ||).

We consider col(A) = the space spanned by the columns of A.

Remark:
Let M = (C1, ..., Cp) be a matrix with p columns.
Let u = (u1, ..., up) be a column vector of p coefficients.
Then:

    M u = u1 C1 + u2 C2 + ... + up Cp

Let (A1, A2) be the columns of A.
Then:

col(A) = { t = (t1, ..., tn)^T such that there exists
           v = (v1, v2)^T with t = A v = v1 A1 + v2 A2 }

For a given vector w, A w belongs to col(A).

If eps is zero then Y belongs to col(A).
Otherwise it is outside of this sub-space.

The solution Ŷ = A w minimizing eps is the orthogonal
projection of Y onto col(A).

We therefore seek the vector w such that Ŷ = A w
is the projection of Y onto col(A).

In a 1D space generated by a vector e_x,
the projection of any vector onto the line is:

    p = <v, e_x> e_x

In dimension n, if the space is generated by the
orthonormal basis (e1, ..., en), then the projection p is:

    p = sum_{i=1}^{n} <v, e_i> e_i

Here our space is generated by the columns of A,
which has two columns (A1, A2).

We can rewrite this space as the set of vectors generated
by (q1, q2) such that (q1, q2) is a pair of orthogonal vectors.

We can apply the Gram–Schmidt process to obtain such a family.

Let q1 = A1.

Project A2 onto q1:
    p = <A2, q1> q1 = <A2, A1> A1

We obtain q2 by subtracting p from A2:
    q2 = A2 - p
       = A2 - <A2, A1> A1

Verification that q1 and q2 are orthogonal:

    <q1, q2>
    = <A1, A2 - <A2, A1> A1>
    = <A1, A2> - <A2, A1><A1, A1>
    = <A1, A2> - <A1, A2>
    = 0

If we then project Y onto col((q1, q2)), the projection is:

    Ŷ = <Y, q1> q1 + <Y, q2> q2

Hence:

    A w = <Y, q1> q1 + <Y, q2> q2

By decomposing A in the new orthonormal basis : A = QR
We obtain two matrix :
Q = [q1, q2] and R = {R_ij} = {<Ai; qj>} (which is triangular)
Then, We can translate our system into a triangular system,
facilitating resolution starting from the highest-order
polynomial coefficient.

In our case, for the linear equation y = a x + b:
 [R11, R12] [w1 = b] == Q^T.Ŷ
 [0  , R22] [w2 = a]

 Therefore we solve for a then for b.
 
This technique is valid for higher-order fits as well as R is triangular.
"""

#############
# FUNCTIONS #
#############
def graham_schmidt(B:np.ndarray)->np.ndarray:
    """Return an orthogonal basis from a given B basis

    Args:
        B (np.ndarray): B basis
    """
   
    B_ortho = []
    for i in range(len(B)):
        e_i = B[i]
        for j in range (len(B_ortho)):
            e_j = B_ortho[j]
            p_j = np.linalg.vecdot(e_i, e_j)*e_j/np.linalg.vecdot(e_j, e_j)
            e_i = e_i - p_j
        B_ortho.append(e_i)
    return(B_ortho)


def regression_projection_vectorielle(X:np.ndarray, Y:np.ndarray, d:int=1):
    """Performs polynomial regression by projecting Y vector onto the regression subs-space.
        Solves the system by reframming it triangularly

    Args:
        X (np.ndarray): n samples of real values
        Y (np.ndarray): n samples of real values
        d (int, optional): Fitting polynome degree. Defaults to 1.
    """

    A = np.array([[xi**(d-i) for i in range(d+1)] for xi in X])

    col_A = np.array([A[:, i] for i in range(d+1)])
    
    # Graham-Schmidt :
    col_A_orthogonal = graham_schmidt(col_A)
    col_A_orthonormal = [e/np.linalg.norm(e) for e in col_A_orthogonal]
    
    Y_estimate = np.sum(np.array([np.linalg.vecdot(Y, e)*e for e in col_A_orthonormal]), axis = 0)

    # Matrice triangulaire et base orthogonale
    Q = np.column_stack(col_A_orthonormal)
    R = Q.T @ A # A = QR <=> R = Q^T.A
    QT_Y_estimate = Q.T @ Y_estimate

    # Q^T.Y_estimate = R.w
    w = np.zeros(len(col_A))
    for i in range(len(col_A)-1, -1, -1):
        w[i] = (QT_Y_estimate[i] - np.dot(R[i, i+1:], w[i+1:])) / R[i, i]

    return(w)



########
# MAIN #
########
if __name__ == "__main__":	
    np.random.seed(0) #Reproductibility
    
    ### SAMPLES ###
    nb = 100 #samples
    d = 1 #degree
    X = np.arange(0, nb)
    n = len(X)
    coeff_th = np.array([np.random.randint(-int(n*0.8), int(+n*0.8)) for _ in range (d+1)])
    Y_th = np.sum([coeff_th[i]*X**i for i in range(len(coeff_th))], axis=0)


    # Ajout de bruit pour obtenir Y
    Y = Y_th + n*4 * (np.random.rand(n) - 0.5)

    ### REGRESSION ###
    #Regression par projection et décomposition dans la base orthogonale
    coeff = regression_projection_vectorielle(X, Y, d)

    Y_estimate = np.sum([coeff[len(coeff)-1-i]*X**i for i in range(len(coeff))], axis=0)


    # R_squared(Y_estimate, Y)
    SS_mean = np.sum((Y-np.mean(Y))**2)
    SS_fit = np.sum((Y-Y_estimate)**2)
    R_squared = (SS_mean - SS_fit)/SS_mean


    ### PLOT ###
    f1, ax = plt.subplots()
    ax.plot(X, Y, '*', label = "Signal bruité")
    ax.plot(X, Y_th, 'r--', label = "Signal théorique")
    ax.plot(X, Y_estimate, label = f"Regression linéaire")
    ax.set_title(f"Regression linéaire")
    ax.text(0.4*n , Y_th[np.absolute(Y_th).argmax()]*0.6, 
            s=f"Regression linéaire\n(a, b) = {float(coeff[1]), float(coeff[0])} \n r² = {R_squared}")
    plt.legend()
    plt.grid()
    plt.show()


        

    




