name: CI Python - Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: benv
          python-version: '3.13'

      - name: Run all Python scripts
        env:
          MPLBACKEND: Agg
        shell: bash -el {0}
        run: |
          for script in Python/*.py; do
            echo "Running $script..."
            python "$script"
          done
